# Secret for LLM API Key
# NOTE: This is a template - you must create the actual secret with your API key
# 
# To create the secret:
# kubectl create secret generic ai-assistant-secrets \
#   --from-literal=LLM_API_KEY="your-actual-api-key" \
#   --namespace=your-namespace

apiVersion: v1
kind: Secret
metadata:
  name: ai-assistant-secrets
  labels:
    app: ai-assistant
    component: config
type: Opaque
data:
  # Base64 encoded API key - replace with your actual encoded secret
  # Use: echo -n "your-actual-api-key" | base64
  LLM_API_KEY: eW91ci1hcGkta2V5LWhlcmU=  # "your-api-key-here" (REPLACE THIS)