apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-assistant
  labels:
    app: ai-assistant
    component: backend
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-assistant-reader
  labels:
    app: ai-assistant
    component: rbac
rules:
# Allow reading most resources for troubleshooting and assistance
- apiGroups: [""]
  resources: 
    - "pods"
    - "services"
    - "endpoints"
    - "configmaps"
    - "secrets"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "events"
    - "nodes"
    - "namespaces"
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"
    - "statefulsets"
    - "daemonsets"
  verbs: ["get", "list", "watch"]

- apiGroups: ["extensions"]
  resources:
    - "ingresses"
  verbs: ["get", "list", "watch"]

# OpenShift specific resources
- apiGroups: ["route.openshift.io"]
  resources:
    - "routes"
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps.openshift.io"] 
  resources:
    - "deploymentconfigs"
  verbs: ["get", "list", "watch"]

- apiGroups: ["build.openshift.io"]
  resources:
    - "builds"
    - "buildconfigs"
  verbs: ["get", "list", "watch"]

- apiGroups: ["image.openshift.io"]
  resources:
    - "imagestreams"
    - "imagestreamtags"
  verbs: ["get", "list", "watch"]

# Allow reading logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

# Allow reading metrics (if metrics server is available)
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-assistant-reader-binding
  labels:
    app: ai-assistant
    component: rbac
subjects:
- kind: ServiceAccount
  name: ai-assistant
  namespace: NAMESPACE_PLACEHOLDER
roleRef:
  kind: ClusterRole
  name: ai-assistant-reader
  apiGroup: rbac.authorization.k8s.io

---
# Optional: More permissive role for workshop environments
# Uncomment this if you want the AI to help with resource creation/modification
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: ai-assistant-workshop
#   labels:
#     app: ai-assistant
#     component: rbac
# rules:
# # Everything from the reader role
# - apiGroups: [""]
#   resources: ["*"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# - apiGroups: ["apps", "extensions"]
#   resources: ["*"] 
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# # Restrict some dangerous operations
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "list", "watch"]  # No node modifications
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]  # No RBAC modifications